# -*- coding: utf-8 -*-
"""STA 2101 - Milestone 02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R3PuEK88obZOJwmP8ne2ZfdZs7RxUa9-

# Milestone 02

Implementing Probability Sampling Methods in Python
"""

import pandas as pd
import numpy as np
from IPython.display import display

# Load your dataset
df = pd.read_csv('2025-08-10.csv')
df.head()

"""## Part A — Setup
- Report dataset size (rows, columns)
"""

print("Dataset size:", df.shape)
population_mean = df['temp_c'].mean()

"""## Part B — Simple Random Sampling"""

sample_size = 50
srs = df.sample(n=sample_size, random_state=42)
display(srs.head())
population_mean = df['temp_c'].mean()
print("Population mean:", population_mean)
srs_mean = srs['temp_c'].mean()
print("Sample mean:", srs_mean)

"""## Part C — Systematic Sampling"""

n = 50
k = len(df) // n
start = np.random.randint(0, k)
sys_sample = df.iloc[start::k][:n]
display(sys_sample.head())
sys_mean = sys_sample['temp_c'].mean()
print("Sample mean:", sys_mean)

"""## Part D — Stratified Sampling"""

strata_col = "division"  # your column
sample_size = 50

# proportional fraction for each group
frac = sample_size / len(df)

# stratified sample
stratified_sample = df.groupby(strata_col, group_keys=False).sample(frac=frac, random_state=42)

display(stratified_sample.head())
strat_mean = stratified_sample['temp_c'].mean()
print("Sample mean:", strat_mean)

"""## Part E — Cluster Sampling"""

df['cluster_id'] = df.index // (len(df)//10)  # 10 clusters
selected_clusters = np.random.choice(df['cluster_id'].unique(), size=2, replace=False)
cluster_sample = df[df['cluster_id'].isin(selected_clusters)]
print("Selected clusters:", selected_clusters)
display(cluster_sample.head())
cluster_mean = cluster_sample['temp_c'].mean()
print("Sample mean:", cluster_mean)

"""## Part F — Comparison & Reflection
Compare sample means vs population mean, then write your reflection.
"""

comparison = pd.DataFrame({
    'Method': ['Simple Random', 'Systematic', 'Stratified', 'Cluster'],
    'Sample Mean': [srs_mean, sys_mean, strat_mean, cluster_mean],
    'Population Mean': [population_mean]*4,
    'Difference': [abs(srs_mean - population_mean),
                   abs(sys_mean - population_mean),
                   abs(strat_mean - population_mean),
                   abs(cluster_mean - population_mean)]
})
print(comparison)